version: "3.8"

services:
  flask-app:
    container_name: flask-app
    build:
      context: ./
    ports:
      - 5000:5000
    depends_on:
      - mysql
    networks:
      - two-tier-ntw
    environment:
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DB: "${MYSQL_DB}"
      MYSQL_HOST: "${MYSQL_HOST}"
      MYSQL_USER: "${MYSQL_USER}" 
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  mysql:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./message.sql:/docker-entrypoint-initdb.d/message.sql
    networks:
      - two-tier-ntw
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    environment:
      MYSQL_DB: "${MYSQL_DB}"
      MYSQL_HOST: "${MYSQL_HOST}"

networks:
  two-tier-ntw:
